delete http://localhost:3003/api/blogs/662c966830e098da25c88889
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxPTCB6ZWQiLCJpZCI6IjY2MmIzOWMyNjk5MWU4ZjU2ZWNhMzA4YSIsImlhdCI6MTcxNDE5Nzk5OCwiZXhwIjoxNzE0MjAxNTk4fQ.U9vfM8CSXT8R2cM6Brhk8A_AGWUGkkkYTLMY9xz9g04